function car_tracks = initializeCarTracks()
%Function for initializing car tracks
%   Detailed explanation goes here

car_tracks = struct(...
            'id', {}, ...
            'bbox', {}, ...
            'kalmanFilter', {}, ...
            'age', {}, ...
            'totalVisibleCount', {}, ...
            'consecutiveInvisibleCount', {});

end

