function [car_tracks,nextID] = createNewTracks(params, centroids, bounding_boxes, unassignedDetections, car_tracks, nextID)
        centroids = centroids(unassignedDetections, :);
        bounding_boxes = bounding_boxes(unassignedDetections, :);

        for i = 1:size(centroids, 1)

            centroid = centroids(i,:);
            bbox = bounding_boxes(i, :);

            % Create a Kalman filter object.
            kalmanFilter = configureKalmanFilter('ConstantVelocity', ...
                centroid, [200, 50], [10, 25], 1000);

            % Create a new track.
            newTrack = struct(...
                'id', nextID, ...
                'age', 1, ...
                'bbox', bbox, ...
                'bbox_initial', bbox, ...
                'velocity', 0, ...
                'priority', determinePriority(bbox, params.priorityPolygons), ...
                'kalmanFilter', kalmanFilter, ...
                'totalVisibleCount', 1, ...
                'consecutiveInvisibleCount', 0);

            % Add it to the array of tracks.
            car_tracks(end + 1) = newTrack;

            % Increment the next id.
            nextID = nextID + 1;
        end
    end